const budayaMalangLengkap = [
  {
    id: 1,
    namaBudaya: "Tari Topeng Malangan",
    deskripsiSingkat: "Tarian klasik dengan topeng kayu.",
    asalUsul: "Tari Topeng Malangan diperkirakan sudah ada sejak abad ke-8 Masehi pada masa Kerajaan Kanjuruhan, dan berkembang pesat pada era Singhasari dan Majapahit. Awalnya, tarian ini merupakan bagian dari ritual keagamaan (tantrayana) untuk memuja roh nenek moyang sebelum akhirnya bergeser menjadi kesenian keraton dan hiburan rakyat.",
    penjelasan: "Kesenian ini selalu membawakan lakon dari cerita Panji (kisah cinta Raden Panji Asmarabangun dan Dewi Sekartaji). Ciri khas Topeng Malangan terletak pada pahatan wajah karakternya yang lebih berekspresi, warna topeng yang melambangkan sifat tokoh (merah untuk angkara murka, putih untuk kesucian, hijau untuk kebijaksanaan), dan gerakan tari yang dinamis serta lugas khas Jawa Timuran.",
    kategori: "Seni Tari",
    estimasiBiaya: "Rp 15.000 - Rp 25.000 (Untuk tiket menonton pertunjukan rutin / donasi padepokan). Beli topeng suvenir: Rp 50.000 - Rp 500.000.",
    lokasi: "Padepokan Seni Asmoro Bangun (Desa Karangpandan, Pakisaji) & Kampung Budaya Polowijen.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzDkPTVHm36B4_3NoUQQPVpjmgjDIjPTjC6d9_4pgBcQ&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Tari+Topeng+Malangan"
  },
  {
    id: 2,
    namaBudaya: "Bahasa Walikan (Osob Kiwalan)",
    deskripsiSingkat: "Bahasa terbalik khas Malang.",
    asalUsul: "Bahasa Walikan (Osob Kiwalan) lahir pada masa Agresi Militer Belanda II (sekitar tahun 1949). Bahasa ini diciptakan oleh para pejuang kemerdekaan (Gerilya) di Malang, khususnya kelompok Pasukan Gerilya Rakyat Kota (GRK), sebagai sandi rahasia agar strategi komunikasi mereka tidak disadap oleh mata-mata Belanda.",
    penjelasan: "Cara kerjanya adalah dengan membalik kosakata bahasa Indonesia atau bahasa Jawa dari huruf belakang ke depan, namun dengan pelafalan yang tetap mudah diucapkan. Contoh paling ikonik adalah 'Malang' menjadi 'Ngalam', 'Makan' menjadi 'Nakam', 'Bagus' menjadi 'Sugab', dan 'Tidak' menjadi 'Kadit'. Saat ini, Osob Kiwalan telah menjadi identitas keakraban budaya pop masyarakat Malang.",
    kategori: "Bahasa & Sastra",
    estimasiBiaya: "Gratis (Digunakan dalam percakapan sehari-hari).",
    lokasi: "Tersebar di seluruh penjuru jalanan, warung kopi, dan lingkungan masyarakat Malang Raya.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqHpNokvM2mINwFo9x_p9ErDLdlmTRcfCYpDtyJH-wdg&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Bahasa+Walikan+Malang"
  },
  {
    id: 3,
    namaBudaya: "Kesenian Bantengan",
    deskripsiSingkat: "Seni bela diri dan tarian magis banteng.",
    asalUsul: "Kesenian ini berakar dari seni bela diri pencak silat di wilayah pegunungan Malang Raya (terutama Batu dan Mojokerto). Lahir dari pengamatan para pendekar zaman dahulu terhadap gerakan binatang liar seperti macan, monyet, dan banteng peliharaan. Elemen mistis dimasukkan sebagai medium penghubung dengan roh leluhur penjaga desa.",
    penjelasan: "Bantengan merupakan pertunjukan komunal di mana dua orang pemain masuk ke dalam kostum berupa kepala banteng kayu dengan kain hitam. Tarian ini diiringi musik gamelan yang mengentak. Pada puncaknya, pemain bantengan sering kali mengalami kesurupan (trance) dan bertarung secara simbolis dengan karakter Macanan atau pendekar yang memegang pecut (cambuk).",
    kategori: "Seni Pertunjukan Rakyat",
    estimasiBiaya: "Gratis (Biasa digelar di lapangan desa atau saat karnaval). Jika mengundang grup: Rp 2.000.000 - Rp 5.000.000.",
    lokasi: "Alun-alun Kota Batu, Desa Bumiaji, dan berbagai festival budaya desa di Kabupaten Malang.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6YxPFOOtUcRtW3hUjC20j-FWrObkifi5jB37M-o7Ctw&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Kesenian+Bantengan+Malang"
  },
  {
    id: 4,
    namaBudaya: "Batik Malangan",
    deskripsiSingkat: "Kain batik bermotif ikonik khas Malang.",
    asalUsul: "Batik Malangan dulunya banyak digunakan untuk keperluan upacara tradisional dan pakaian para kaum bangsawan zaman kerajaan. Namun, seiring berjalannya waktu, para pengrajin lokal merevitalisasi batik ini dengan memasukkan unsur-unsur visual yang merepresentasikan identitas lokal daerah Malang modern.",
    penjelasan: "Batik ini memiliki pakem corak yang unik. Tiga motif utama yang paling sering muncul adalah motif Bunga Teratai (menyimbolkan keindahan), motif Topeng Malangan (menyimbolkan seni), dan Tugu Malang (menyimbolkan pusat kota). Warna yang dominan digunakan seringkali cerah dan berani, seperti biru, merah, hijau, dan hitam, yang menggambarkan karakter masyarakat Arek yang tegas.",
    kategori: "Kerajinan & Kriya",
    estimasiBiaya: "Rp 150.000 - Rp 800.000 per kain (Tergantung teknik cap atau tulis tangan).",
    lokasi: "Sentra Batik Celaket (Jalan Jaksa Agung Suprapto) & Kampung Batik Blimbing.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiQbohKbEqGAUCDKFQTiiJH6Pqtc1WgvPui1p6yDE-QA&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Batik+Malangan"
  },
  {
    id: 5,
    namaBudaya: "Jaran Kepang Malangan (Jaranan)",
    deskripsiSingkat: "Tari kuda lumping atraktif khas Jawa Timuran.",
    asalUsul: "Jaranan adalah tarian rakyat legendaris yang mengisahkan pasukan kavaleri berkuda. Di Malang, gaya Jaranan memiliki perpaduan antara Jaranan Kediri dan kesenian lokal, menjadikannya sarana hiburan rakyat sekaligus upacara ruwatan desa (tolak bala).",
    penjelasan: "Berbeda dengan daerah lain, Jaran Kepang Malangan memiliki gerakan yang sangat rancak dan agresif, mengikuti irama kendang yang cepat. Pemain menaiki anyaman bambu berbentuk kuda. Pertunjukan ini juga melibatkan atraksi kekebalan tubuh seperti makan beling atau menyemburkan api saat penarinya sedang dalam kondisi 'ndadi' atau kerasukan.",
    kategori: "Seni Pertunjukan Rakyat",
    estimasiBiaya: "Gratis (Ditonton di hajatan atau lapangan). Menyewa untuk acara mulai dari Rp 3.000.000.",
    lokasi: "Sering dijumpai di acara bersih desa atau perayaan HUT RI di wilayah Kabupaten Malang.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVkyKdiUF-nr5nxkFoItKU6MeuMkHp-J5-xrAZ7K2M-w&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Jaran+Kepang+Malangan"
  },
  {
    id: 6,
    namaBudaya: "Ludruk Malangan",
    deskripsiSingkat: "Drama teater komedi tradisional rakyat.",
    asalUsul: "Ludruk adalah seni drama tradisional yang lahir dari kalangan rakyat jelata Jawa Timur sebagai media hiburan sekaligus kritik sosial pada masa penjajahan. Ludruk Malangan membawa ciri khas dialek dan gaya guyonan yang lebih kasar namun akrab khas orang Malang (Arekan).",
    penjelasan: "Ludruk sepenuhnya diperankan oleh laki-laki (termasuk pemeran wanita yang disebut *travesti*). Pertunjukan ini dibuka dengan Tari Remo, disusul oleh nyanyian parikan (pantun Jawa), dan diakhiri dengan drama kehidupan sehari-hari (bukan cerita mitos seperti ketoprak). Guyonan spontan tanpa naskah ketat adalah daya tarik utama Ludruk.",
    kategori: "Teater & Sastra",
    estimasiBiaya: "Rp 20.000 - Rp 50.000 (Tiket pertunjukan gedung seni).",
    lokasi: "Gedung Kesenian Gajayana, RRI Malang, atau panggung-panggung desa.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPiHsG_f-1tjiTVQpxS3NORTBPn5J6igNy2UDvaLhWOQ&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Ludruk+Malangan"
  },
  {
    id: 7,
    namaBudaya: "Grebeg Suro Gunung Kawi",
    deskripsiSingkat: "Ritual budaya agung malam 1 Suro.",
    asalUsul: "Tradisi ini berawal dari masyarakat sekitar Pesarean Gunung Kawi (makam Eyang Jugo dan Eyang Sujo) yang merupakan tokoh penyebar agama Islam dan pelawan penjajah. Tradisi ini dilakukan turun-temurun sejak puluhan tahun lalu untuk memperingati Tahun Baru Islam (1 Muharram) atau 1 Suro dalam penanggalan Jawa.",
    penjelasan: "Prosesi Grebeg Suro melibatkan pembakaran patung raksasa (ogoh-ogoh) yang melambangkan nafsu angkara murka manusia yang harus dimusnahkan. Selain itu, ada pawai sesaji hasil bumi, tarian sakral, dan rebutan gunungan tumpeng oleh ribuan masyarakat yang percaya bahwa hasil bumi tersebut akan membawa keberkahan dan kelancaran rezeki.",
    kategori: "Ritual & Adat",
    estimasiBiaya: "Gratis untuk penonton umum.",
    lokasi: "Kawasan Pesarean Gunung Kawi, Kecamatan Wonosari, Kabupaten Malang.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDP9ZyKBnGaEhtpkDNEtMIm_vCu6fAliQF1CbV2r7Dqg&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Grebeg+Suro+Gunung+Kawi"
  },
  {
    id: 8,
    namaBudaya: "Wayang Topeng Malangan",
    deskripsiSingkat: "Seni wayang orang menggunakan topeng.",
    asalUsul: "Wayang Topeng merupakan perluasan dari Tari Topeng Malangan, namun disajikan dalam format teater panjang mirip wayang orang. Kesenian ini dulunya disukai oleh para Raja Jawa Timur sebagai hiburan keraton yang elit.",
    penjelasan: "Pertunjukan ini dimainkan oleh puluhan aktor yang semuanya mengenakan topeng kayu. Karena mulut tertutup topeng, para pemain biasanya tidak berdialog secara langsung. Dialog akan disuarakan oleh seorang Dalang yang duduk di dekat gamelan (seperti wayang kulit). Pertunjukan ini berdurasi panjang dan memiliki filosofi mendalam tentang dualisme kebaikan dan kejahatan.",
    kategori: "Seni Pertunjukan Tradisional",
    estimasiBiaya: "Rp 15.000 - Rp 30.000 (Tiket reguler padepokan).",
    lokasi: "Padepokan Seni Mangun Dharma (Tumpang, Kabupaten Malang).",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkLTTl_Cdgz6dqQAxWcYpXDUUVrHnduQ1CLgBBD6yY9w&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Wayang+Topeng+Malangan"
  },
  {
    id: 9,
    namaBudaya: "Tari Beskalan",
    deskripsiSingkat: "Tarian penyambut tamu kehormatan.",
    asalUsul: "Beskalan berasal dari kata 'Bakalan' yang berarti awal atau pembuka. Pada zaman dahulu, tari Beskalan digunakan sebagai ritual ritus kesuburan tanah (membuka lahan baru) dan ditarikan oleh laki-laki yang berpakaian wanita (tandak). Kini berevolusi menjadi tarian penyambutan tamu besar.",
    penjelasan: "Tarian ini sangat lincah, anggun, dan diiringi alunan gamelan Jawa Timuran yang ritmis. Penari Beskalan identik dengan riasan wajah yang cantik, menggunakan selendang (sampur), dan mahkota cunduk mentul di kepalanya. Gerakannya merepresentasikan keanggunan, keramahan, dan kelincahan perempuan Malang.",
    kategori: "Seni Tari",
    estimasiBiaya: "Gratis saat acara festival. Tarif mengundang sanggar: Rp 1.500.000 - Rp 3.000.000.",
    lokasi: "Ditampilkan di berbagai peresmian acara pemerintah atau sanggar tari di Malang Raya.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQXxuGL9mMn1Y5laF4xQ5USIGJP39-CNpxZXqxrY_3mw&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Tari+Beskalan+Malang"
  },
  {
    id: 10,
    namaBudaya: "Tari Bapang",
    deskripsiSingkat: "Tari gagah karakter berhidung panjang.",
    asalUsul: "Bapang adalah salah satu karakter utama dalam lakon Panji pada Wayang Topeng Malangan. Karakter ini sering disebut sebagai Tumenggung Bapang, seorang panglima perang dari Kerajaan Sabrang yang memiliki sifat temperamental namun gagah.",
    penjelasan: "Tari Bapang sering dipentaskan secara mandiri di luar cerita wayang utuh karena gerakannya yang sangat ikonik. Ciri khasnya adalah topeng merah menyala dengan hidung panjang melengkung ke atas, mata melotot, dan kumis tebal. Gerakannya lebar, gagah, membentangkan tangan seolah membusungkan dada memamerkan kekuasaannya.",
    kategori: "Seni Tari",
    estimasiBiaya: "Rp 15.000 (Tiket di Padepokan Asmoro Bangun).",
    lokasi: "Padepokan Asmoro Bangun, Malang & Berbagai festival budaya kota.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_ZZkOH7H6gCcXSPNcUK6jx1R1zCF5cgMwtIb9sWvuOA&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Tari+Bapang+Malang"
  },
  {
    id: 11,
    namaBudaya: "Seni Kentrung Malangan",
    deskripsiSingkat: "Seni tutur lisan dengan alat musik tabuh.",
    asalUsul: "Seni Kentrung berkembang pada masa penyebaran agama Islam di Jawa Timur. Kata 'Kentrung' berasal dari bunyi alat musik rebana atau terbang yang dipukul (trung... trung...). Seni ini digunakan oleh para wali dan kiai untuk berdakwah menyebarkan nilai-nilai Islam dan moral kehidupan.",
    penjelasan: "Kentrung Malangan dimainkan oleh satu atau dua orang seniman (Dalang Kentrung) yang bercerita sambil menabuh terbang/rebana. Cerita yang diangkat biasanya adalah kisah para nabi, legenda rakyat (seperti Amir Hamzah), hingga sisipan kritik sosial yang dibawakan dengan banyolan (komedi) segar khas logat Arekan.",
    kategori: "Seni Sastra & Musik",
    estimasiBiaya: "Sangat jarang dikomersialkan, biasanya ditonton gratis di acara budaya atau donasi ke seniman.",
    lokasi: "Acara-acara kebudayaan literasi atau festival seni sastra di kampus/kota Malang.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEAA3W2AfNXRWD2INcIRg24BNbeGWcLBbhIAoBiTEnvg&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Seni+Kentrung+Malangan"
  },
  {
    id: 12,
    namaBudaya: "Petik Laut Sendang Biru",
    deskripsiSingkat: "Ritual syukur nelayan pantai selatan.",
    asalUsul: "Tradisi yang lahir sejak puluhan tahun lalu dari komunitas nelayan di wilayah pesisir selatan Kabupaten Malang. Ritual ini merupakan wujud syukur kepada Tuhan atas rezeki tangkapan ikan yang melimpah sekaligus doa permohonan keselamatan saat melaut.",
    penjelasan: "Rangkaian acara dipusatkan di Pantai Sendang Biru pada tanggal 27 September setiap tahunnya. Nelayan akan membuat miniatur perahu (gitik) yang diisi sesaji berupa kepala sapi, hasil bumi, dan makanan jajanan pasar. Miniatur ini kemudian diarak dan dilarungkan (dilepas) ke tengah lautan lepas, diikuti ratusan perahu nelayan yang dihias meriah.",
    kategori: "Ritual & Adat",
    estimasiBiaya: "Gratis (Bisa ditonton langsung oleh wisatawan di Pantai Sendang Biru).",
    lokasi: "Pantai Sendang Biru, Kecamatan Sumbermanjing Wetan, Kabupaten Malang.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQAZZwVgpxQEru2aFH1wNeZkwfl5yBnlqhIupftISyYw&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Petik+Laut+Sendang+Biru"
  },
  {
    id: 13,
    namaBudaya: "Wayang Kulit Gagrak Malangan",
    deskripsiSingkat: "Wayang kulit dengan logat dan cengkok Malang.",
    asalUsul: "Wayang Kulit Malangan berkembang di pinggiran Kerajaan Majapahit dan mendapat pengaruh kuat dari budaya pesisir utara dan Mataraman, namun beradaptasi dengan watak keras dan lugas masyarakat pedalaman Malang.",
    penjelasan: "Berbeda dengan Gagrak (gaya) Surakarta atau Yogyakarta yang halus, Gagrak Malangan sangat dinamis. Suluk (nyanyian dalang) dilantunkan dengan tempo lebih cepat dan nada tinggi. Guyonan para Punakawan sangat menonjolkan bahasa Walikan (Kiwalan) dan celetukan-celetukan khas keseharian Arek Malang yang blak-blakan.",
    kategori: "Seni Pertunjukan Tradisional",
    estimasiBiaya: "Menyewa Dalang dan Kru mulai dari Rp 10.000.000 - Rp 25.000.000 per malam (Gratis untuk penonton).",
    lokasi: "Acara hajatan warga lokal, Bersih Desa, atau di RRI Malang.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJQt_Embj0eVe2X1kzBr5cDmJDr4apAYVmzAhtlnvR5Q&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Wayang+Kulit+Gagrak+Malangan"
  },
  {
    id: 14,
    namaBudaya: "Jaranan Dor",
    deskripsiSingkat: "Varian jaranan mistis beriringan bedug (dor).",
    asalUsul: "Disebut 'Dor' karena irama musiknya didominasi oleh suara bedug (jidor) yang berbunyi 'dor.. dor..'. Kesenian ini sangat populer di kawasan pesisir Jawa Timur dan pinggiran Jombang-Malang sejak era kolonial.",
    penjelasan: "Berbeda dengan Jaran Kepang, penari Jaranan Dor biasanya tidak menggunakan anyaman kuda yang rumit. Fokus utama terletak pada atraksi kekebalan tubuh, tarian cemeti (pecut), dan prosesi kesurupan (trance) massal. Suasana magis sangat kental, dengan bau kemenyan yang dibakar selama pertunjukan berlangsung.",
    kategori: "Seni Pertunjukan Rakyat",
    estimasiBiaya: "Gratis (Tontonan terbuka di lapangan atau jalan desa).",
    lokasi: "Sering dipertunjukkan saat bulan Suro atau karnaval desa di pelosok Kabupaten Malang.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSH2th05eRR61ZV-8WG2B32opiP-9kBiZ8bvH9R0z5oEA&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Jaranan+Dor+Malang"
  },
  {
    id: 15,
    namaBudaya: "Tradisi Barikan",
    deskripsiSingkat: "Kenduri keselamatan di perempatan jalan.",
    asalUsul: "Barikan adalah tradisi selamatan (kenduri) akar rumput yang sudah mengakar kuat sejak sebelum masa kemerdekaan. Biasanya dilakukan menjelang hari peringatan kemerdekaan 17 Agustus atau pada malam 1 Suro.",
    penjelasan: "Masyarakat tingkat RT atau RW akan berkumpul bersama di malam hari, biasanya duduk lesehan di perempatan jalan kampung. Setiap keluarga membawa makanan ringan atau tumpeng kecil untuk kemudian didoakan bersama oleh pemuka agama setempat. Setelah doa, seluruh makanan akan dibagikan dan dimakan bersama sebagai simbol kerukunan dan tolak bala.",
    kategori: "Ritual & Adat",
    estimasiBiaya: "Gratis (Setiap warga membawa makanan sendiri/swadaya).",
    lokasi: "Hampir seluruh kampung dan perumahan di Malang pada malam 16 Agustus.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5CaJ_A4Jfsq5mEHjbaJuZ631Xh0mDdYAt96Z-bJmq3w&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Tradisi+Barikan+Malang"
  },
  {
    id: 16,
    namaBudaya: "Yadnya Kasada Suku Tengger Ngadas",
    deskripsiSingkat: "Ritual persembahan ke kawah Gunung Bromo.",
    asalUsul: "Tradisi kuno masyarakat Suku Tengger yang diyakini sebagai keturunan langsung pelarian Majapahit (Roro Anteng dan Joko Seger). Desa Ngadas di Kecamatan Poncokusumo adalah kantong terbesar Suku Tengger di wilayah Malang.",
    penjelasan: "Diadakan pada hari ke-14 bulan Kasada (penanggalan Tengger). Warga Ngadas dari Malang akan berjalan kaki atau naik jeep membawa ongkek (keranjang bambu) berisi hasil bumi dan ternak untuk dilemparkan ke dalam kawah Gunung Bromo. Ini adalah bentuk penebusan janji leluhur agar diberi keselamatan dari amarah gunung berapi.",
    kategori: "Ritual & Adat Keagamaan",
    estimasiBiaya: "Gratis untuk disaksikan, namun perlu bayar tiket masuk Taman Nasional Bromo (Rp 34.000).",
    lokasi: "Desa Wisata Ngadas (Malang) menuju Kawah Gunung Bromo.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgMqPvsV3JgGIZP1yMAcdtJ_-ciSJTpkx10fcZ1KG50g&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Yadnya+Kasada+Suku+Tengger"
  },
  {
    id: 17,
    namaBudaya: "Upacara Karo (Suku Tengger)",
    deskripsiSingkat: "Hari Raya Agung persaudaraan Suku Tengger.",
    asalUsul: "Perayaan bulan kedua (Karo) dalam kalender Suku Tengger. Asal-usulnya berkaitan dengan penciptaan manusia pertama serta legenda dua abdi (Setya dan Tuhu) pembawa pusaka Aji Saka yang saling bertarung karena kesalahpahaman.",
    penjelasan: "Ini adalah 'lebarannya' masyarakat Tengger di Desa Ngadas, Malang. Acara berlangsung meriah selama berhari-hari. Terdapat prosesi Tari Sodoran (melambangkan pembuahan), arak-arakan sesaji, dan tradisi unjung-unjung (saling berkunjung dari rumah ke rumah) untuk memohon maaf tanpa memandang status sosial dan agama.",
    kategori: "Ritual & Adat",
    estimasiBiaya: "Gratis (Wisatawan bisa berkunjung langsung ke Desa Ngadas saat perayaan).",
    lokasi: "Desa Wisata Ngadas, Kecamatan Poncokusumo, Kabupaten Malang.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDI-vPCkITl_NlKSWipeqtii-zriCkvsyURIqAGFgO9w&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Upacara+Karo+Suku+Tengger"
  },
  {
    id: 18,
    namaBudaya: "Upacara Entas-Entas",
    deskripsiSingkat: "Ritual penyucian roh leluhur Tengger.",
    asalUsul: "Sebuah ritual kematian tingkat akhir dalam agama Hindu Tengger yang wajib dilakukan oleh keluarga yang ditinggalkan (setelah hari ke-1000 kematian) agar roh leluhur bisa di-'entas' (diangkat) masuk ke alam nirwana.",
    penjelasan: "Berpusat pada pembuatan boneka simbolis dari daun kelapa atau ilalang (disebut Petra) yang melambangkan roh almarhum. Boneka ini didoakan oleh Dukun Pandita Tengger, diberi pakaian, disucikan dengan air suci, dan akhirnya dibakar. Abunya dilarung atau dikubur. Ritual ini sangat sakral dan menghabiskan biaya besar bagi warga pelaksana.",
    kategori: "Ritual & Adat Keagamaan",
    estimasiBiaya: "Ratusan juta bagi penyelenggara, namun gratis untuk disaksikan masyarakat dan pelancong.",
    lokasi: "Desa Ngadas, Poncokusumo, Malang.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR65iZdfq7XT5o__ylMuqQe3ggkesPZImzRNLLZ7BxtPA&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Upacara+Entas-Entas+Tengger"
  },
  {
    id: 19,
    namaBudaya: "Terbang Jidor Malangan",
    deskripsiSingkat: "Kesenian selawatan bernuansa ritmis.",
    asalUsul: "Seni musik perpaduan budaya Islam Timur Tengah dengan instrumen perkusi lokal Jawa. Berkembang pesat di pesantren dan desa-desa santri di wilayah Malang sebagai media dakwah.",
    penjelasan: "Menggunakan empat instrumen utama berupa rebana (terbang) berukuran besar dan satu buah bedug kecil (jidor). Para pemukul rebana melantunkan syair-syair salawat Nabi atau Kitab Al-Barzanji dalam bahasa Arab dan Jawa. Iramanya sangat rancak dan membangkitkan semangat (heroik).",
    kategori: "Seni Sastra & Musik",
    estimasiBiaya: "Gratis (Tampil di pengajian akbar atau peringatan Maulid Nabi).",
    lokasi: "Pesantren-pesantren di Kabupaten Malang dan Kota Batu.",
    fotoBudaya: "https://i.ytimg.com/vi/czsJEYjvJLY/hq720.jpg?sqp=-oaymwE7CK4FEIIDSFryq4qpAy0IARUAAAAAGAElAADIQj0AgKJD8AEB-AH-CYAC0AWKAgwIABABGFggXihlMA8=&rs=AOn4CLD_qy2Sz1dd0DeTxFVWFbieMq21Ew",
    linkYoutube: "https://www.youtube.com/results?search_query=Terbang+Jidor+Malang"
  },
  {
    id: 20,
    namaBudaya: "Tari Remo Malangan",
    deskripsiSingkat: "Tarian pembuka ludruk dengan gaya gagah.",
    asalUsul: "Meski Tari Remo identik dengan Jombang dan Surabaya, Malang memiliki gaya Remo tersendiri yang disebut Remo Malangan atau Remo Putri. Diciptakan pada era perkembangan seni Ludruk sebagai tarian pembuka.",
    penjelasan: "Tari Remo Malangan dicirikan oleh gerakan yang lebih kaku, tegas, dan patah-patah dibanding Remo Surabaya yang mengalir. Busana yang dikenakan biasanya berupa sabuk tenun ikat, celana panjen, keris di punggung, dan giring-giring (lonceng kecil) di pergelangan kaki yang bergemerincing setiap penari menghentakkan kaki.",
    kategori: "Seni Tari",
    estimasiBiaya: "Sering dipaketkan dengan tiket Ludruk (Rp 20.000 - Rp 50.000).",
    lokasi: "Gedung kesenian, panggung Ludruk, dan upacara penyambutan tamu besar.",
    fotoBudaya: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxgDgPXoELEIFC9NzF57n27PEyNXMVuhOVrMcGQ2292w&s=10",
    linkYoutube: "https://www.youtube.com/results?search_query=Tari+Remo+Malangan"
  },
  {
    id: 21,
    namaBudaya: "Tradisi Nyadran / Bersih Desa",
    deskripsiSingkat: "Ritual sedekah bumi dan penghormatan leluhur.",
    asalUsul: "Tradisi turun temurun masyarakat agraris di Jawa. Di Malang, tradisi ini biasa dilakukan pada bulan Selo (penanggalan Jawa) sebagai bentuk rasa syukur atas panen dan memohon dijauhkan dari marabahaya.",
    penjelasan: "Warga desa bergotong-royong membersihkan makam leluhur desa (punden). Puncak acara diisi dengan kenduri akbar membawa ancak (wadah bambu) berisi hasil bumi. Pada malam harinya, desa akan menggelar pertunjukan wayang kulit semalam suntuk, ludruk, atau jaranan sebagai hiburan rakyat sekaligus pelengkap ritual.",
    kategori: "Ritual & Adat",
    estimasiBiaya: "Gratis untuk pengunjung. Pendanaan murni dari iuran swadaya warga desa.",
    lokasi: "Diadakan bergiliran di balai-balai desa seluruh wilayah Kabupaten Malang.",
    fotoBudaya: "https://cdn.kemenag.go.id/storage/posts/16_9/big/1645079189.jpeg",
    linkYoutube: "https://www.youtube.com/results?search_query=Tradisi+Nyadran+Bersih+Desa+Malang"
  }
];

// Mapping data agar propertinya lebih ringkas saat digunakan di komponen React (BudayaPage / DetailBudayaModal)
export const budayaData = budayaMalangLengkap.map((item) => ({
  id: item.id,
  name: item.namaBudaya,
  shortDesc: item.deskripsiSingkat,
  history: item.asalUsul,
  desc: item.penjelasan,
  category: item.kategori,
  price: item.estimasiBiaya,
  location: item.lokasi,
  image: item.fotoBudaya,
  youtubeLink: item.linkYoutube
}));